/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cp2_lab_final;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 1234
 */
public class buy_loadBalance_frame extends javax.swing.JFrame {
    wallet_frame wframe = new wallet_frame();
    
    /**
     * Creates new form buy_loadBalance_frame
     */
    public buy_loadBalance_frame() {
        wframe.setVisible(true);
        initComponents();
        int i=1;
        while(valuableManager.name_of(i)!=null){
            jComboBox1.addItem(valuableManager.name_of(i));
            i++;
        }
    }
    
    public buy_loadBalance_frame(String selectedName) {
        wframe.setVisible(true);
    initComponents();
    int i = 1;
    boolean matched = false;

    while (valuableManager.name_of(i) != null) {
        String name = valuableManager.name_of(i);
        jComboBox1.addItem(name);
        if (name.equals(selectedName)) {
            matched = true;
        }
        i++;
    }

    // Eğer listedeki veriler arasında varsa seç
    if (matched) {
        jComboBox1.setSelectedItem(selectedName);
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valname_lbl = new javax.swing.JLabel();
        valprice_lbl = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        buy_txt = new javax.swing.JTextField();
        buy_bttn = new javax.swing.JButton();
        maxbuy_bttn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        topup_txt = new javax.swing.JTextField();
        topup_bttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buy&Top Up Balance Page");

        valname_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        valprice_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1İtemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("How many do you want to buy?");

        buy_bttn.setText("Buy");
        buy_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buy_bttnActionPerformed(evt);
            }
        });

        maxbuy_bttn.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        maxbuy_bttn.setText("max buy");
        maxbuy_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxbuy_bttnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Top Up Balance");

        topup_bttn.setText("Top Up");
        topup_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topup_bttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(maxbuy_bttn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(177, 177, 177)
                            .addComponent(topup_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(topup_bttn))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(178, 178, 178)
                            .addComponent(buy_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buy_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addComponent(valname_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(54, 54, 54)
                            .addComponent(valprice_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(valname_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(valprice_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buy_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buy_bttn))
                .addGap(6, 6, 6)
                .addComponent(maxbuy_bttn)
                .addGap(42, 42, 42)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(topup_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(topup_bttn))
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1İtemStateChanged
       valname_lbl.setText(valuableManager.name_of(jComboBox1.getSelectedIndex()+1));
       valprice_lbl.setText(String.valueOf(valuableManager.price_of(jComboBox1.getSelectedIndex()+1)));
    }//GEN-LAST:event_jComboBox1İtemStateChanged

    private void topup_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topup_bttnActionPerformed
       
        
        int topup;
        try{
             topup = Integer.parseInt(topup_txt.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Please enter an integer number");
            return;
        }
            if(topup>100000){
            JOptionPane.showMessageDialog(rootPane, "You can only add up to 100,000 as balance.");
            return;
            }
            else if(topup<=0){
            JOptionPane.showMessageDialog(rootPane, "The added balance must be greater than 0.");
            return;
            }
            walletManager.TopUpBalance(topup);
           wframe.setVisible(false);
           wframe = new wallet_frame();
           wframe.setVisible(true);
           
           
    }//GEN-LAST:event_topup_bttnActionPerformed

    private void buy_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buy_bttnActionPerformed
         int adet;
        try{
             adet = Integer.parseInt(buy_txt.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Please enter an integer number");
            return;
        }
        
        if(adet <=0){
        JOptionPane.showMessageDialog(rootPane,"Please enter a positive numeric value");
        return;
        }
        try {
            
            walletManager.buy(jComboBox1.getSelectedIndex()+1, adet);
        } catch (IOException ex) {
            Logger.getLogger(buy_loadBalance_frame.class.getName()).log(Level.SEVERE, null, ex);
        }
           wframe.setVisible(false);
           wframe = new wallet_frame();
           wframe.setVisible(true);
        
    }//GEN-LAST:event_buy_bttnActionPerformed

    private void maxbuy_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxbuy_bttnActionPerformed
        if((int)(userManager.getBalance()/valuableManager.price_of(jComboBox1.getSelectedIndex()+1))<100000){
            buy_txt.setText(String.valueOf((int)(userManager.getBalance()/valuableManager.price_of(jComboBox1.getSelectedIndex()+1))));
        
        }
        else
            buy_txt.setText("100000");
    }//GEN-LAST:event_maxbuy_bttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buy_loadBalance_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buy_loadBalance_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buy_loadBalance_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buy_loadBalance_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buy_loadBalance_frame().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buy_bttn;
    private javax.swing.JTextField buy_txt;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton maxbuy_bttn;
    private javax.swing.JButton topup_bttn;
    private javax.swing.JTextField topup_txt;
    private javax.swing.JLabel valname_lbl;
    private javax.swing.JLabel valprice_lbl;
    // End of variables declaration//GEN-END:variables
}

