/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cp2_lab_final;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 1234
 */
public class sell_frame extends javax.swing.JFrame {
    wallet_frame frame = new wallet_frame();
    /**
     * Creates new form sell_frame
     */
    public sell_frame() {
        frame.setVisible(true);
        initComponents();
        int i=1;
        while(valuableManager.name_of(i)!=null ){
            
            if(userManager.does_have(i)!=-1)
                jComboBox1.addItem(valuableManager.name_of(i));
            
            i++;
        }
    }
    public sell_frame(String selectedName) {
    frame.setVisible(true);
    initComponents();
    boolean matched = false;
    int i = 1;
    while (valuableManager.name_of(i) != null) {
        if (userManager.does_have(i) != -1) {
            String name = valuableManager.name_of(i);
            jComboBox1.addItem(name);
            if (name.equals(selectedName)) {
                matched = true;
            }
        }
        i++;
    }

    if (matched) {
        jComboBox1.setSelectedItem(selectedName);
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        sell_sth_txt = new javax.swing.JTextField();
        sell_sth_bttn = new javax.swing.JButton();
        sell_all_bttn = new javax.swing.JButton();
        valname_lbl = new javax.swing.JLabel();
        valprice_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sell Page");

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1İtemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("How Many Do You Want To Sell?");

        sell_sth_bttn.setText("Sell");
        sell_sth_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sell_sth_bttnActionPerformed(evt);
            }
        });

        sell_all_bttn.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        sell_all_bttn.setText("Sell All");
        sell_all_bttn.setMaximumSize(new java.awt.Dimension(73, 24));
        sell_all_bttn.setMinimumSize(new java.awt.Dimension(73, 24));
        sell_all_bttn.setPreferredSize(new java.awt.Dimension(73, 24));
        sell_all_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sell_all_bttnActionPerformed(evt);
            }
        });

        valname_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        valprice_lbl.setFont(valprice_lbl.getFont().deriveFont((float)14));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sell_all_bttn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sell_sth_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                                .addGap(62, 62, 62))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(valname_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valprice_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sell_sth_bttn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valname_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valprice_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sell_sth_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sell_sth_bttn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sell_all_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1İtemStateChanged
       valname_lbl.setText(valuableManager.name_of(valuableManager.id_of(String.valueOf(jComboBox1.getSelectedItem()))));
       valprice_lbl.setText(String.valueOf(valuableManager.price_of(valuableManager.id_of(String.valueOf(jComboBox1.getSelectedItem())))));    }//GEN-LAST:event_jComboBox1İtemStateChanged

    private void sell_sth_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sell_sth_bttnActionPerformed
       int adet;
        try{
             adet = Integer.parseInt(sell_sth_txt.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "tam sayı giriniz");
            return;
        }
        try {
            walletManager.sell(valuableManager.id_of(String.valueOf(jComboBox1.getSelectedItem())), adet);
        } catch (IOException ex) {
            Logger.getLogger(sell_frame.class.getName()).log(Level.SEVERE, null, ex);
        }
        jComboBox1.removeAllItems();
                int i=1;
        while(valuableManager.name_of(i)!=null ){
            
            if(userManager.does_have(i)!=-1)
                jComboBox1.addItem(valuableManager.name_of(i));
            
            i++;
        }
        frame.setVisible(false);
        frame = new wallet_frame();
        frame.setVisible(true);

    }//GEN-LAST:event_sell_sth_bttnActionPerformed

    private void sell_all_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sell_all_bttnActionPerformed
        
        sell_sth_txt.setText(String.valueOf(userManager.does_have(valuableManager.id_of(String.valueOf(jComboBox1.getSelectedItem())))));

    }//GEN-LAST:event_sell_all_bttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sell_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sell_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sell_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sell_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sell_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton sell_all_bttn;
    private javax.swing.JButton sell_sth_bttn;
    private javax.swing.JTextField sell_sth_txt;
    private javax.swing.JLabel valname_lbl;
    private javax.swing.JLabel valprice_lbl;
    // End of variables declaration//GEN-END:variables
}
